#pragma config(Sensor, in1,    leftBallSensor, sensorAnalog)
#pragma config(Sensor, in2,    frontOppSensor, sensorAnalog)
#pragma config(Sensor, in3,    leftFrontLimit, sensorAnalog)
#pragma config(Sensor, in4,    rightFrontLimit, sensorAnalog)
#pragma config(Sensor, in5,    rightBallSensor, sensorAnalog)
#pragma config(Sensor, in6,    backOppSensor,  sensorAnalog)
#pragma config(Sensor, dgtl1,  backLeftLimit,  sensorDigitalIn)
#pragma config(Sensor, dgtl2,  backRightLimit, sensorDigitalIn)
#pragma config(Sensor, dgtl3,  collectorLimit, sensorDigitalIn)
#pragma config(Sensor, dgtl4,  mainLimit,      sensorDigitalIn)
#pragma config(Sensor, dgtl5,  compass_LSB,    sensorDigitalIn)
#pragma config(Sensor, dgtl6,  compass_Bit2,   sensorDigitalIn)
#pragma config(Sensor, dgtl7,  compass_Bit3,   sensorDigitalIn)
#pragma config(Sensor, dgtl8,  compass_MSB,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  leftBackLine,   sensorDigitalIn)
#pragma config(Sensor, dgtl10, rightBackLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl11, leftFrontLine,  sensorDigitalIn)
#pragma config(Sensor, dgtl12, rightFrontLine, sensorDigitalIn)
#pragma config(Motor,  port2,           left_motor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right_motor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           roller_motor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           gate_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "globals.h"

/* RUN MAIN CODE */
task main()
{

	while(SensorValue[mainLimit]){
		;
 	}
	delay(500);
	init();
	startTask(getCurrOrientation);
	startTask(updateSensors);
	startTask(ball_detection);

	startTask(opponent_detection);
	startTask(stateControl);
	delay(1000);
	startTask(check_line);


	while(1) {
		// writeDebugStreamLine("ORIENTATION: %d\n", CURR_ORIENTATION);
		if (SensorValue[mainLimit] == 0){
			stopAllTasks();
			stop_all_motors();
			break;
		}
	}
}

// /* TEST CODE */
//   task main()
//   {
//  	while(SensorValue[mainLimit]){
//  		;
//   	}
//  	delay(500);
//  	motorTestRun('r');
//   	while(1) {
//   		if (SensorValue[mainLimit] == 0){
//  			stop_all_motors();
//  			break;
//  		}
//   		continue;
//   	}
//   	break;
//   }
